NO_REQUEST = 0
REGISTRATIONS_REQUEST = 1
LOGIN_REQUEST = 2
TOPIC_CREATE_REQUEST = 3
PUSH_REQUEST = 4
PULL_REQUEST = 5
SUBSCRIBE_REQUEST = 6
REQUEST_SUCCESS = 1
REQUEST_FAILURE = 0

DATABASE_USER = 'root'
DATABASE_PASSWORD = "p#E@3xq="
DATEBASE_NAME = 'IMQ_system'

MESSAGE_STATUS_READY = 1
MESSAGE_STATUS_DELIVERED = 2
MESSAGE_STATUS_DEAD = 3
